dist: bionic

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker pull $DOCKER_USERNAME/poissontris:latest
      - docker build --build-arg CACHE_DATE=$(date) --cache-from $DOCKER_USERNAME/poissontris -t $DOCKER_USERNAME/poissontris-deps .
      - docker images
      - docker push $DOCKER_USERNAME/poissontris
