dist: bionic

branches:
  only:
  - master
  - test

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull $DOCKER_USERNAME/poissontris:latest
    - docker build -t $DOCKER_USERNAME/poissontris --build-arg CACHE_DATE="$(date)" --cache-from $DOCKER_USERNAME/poissontris:"$TRAVIS_BRANCH" .
    - docker images
    - docker push $DOCKER_USERNAME/poissontris:"$TRAVIS_BRANCH"
before_install:
  - openssl aes-256-cbc -K $encrypted_f0da1fbc7955_key -iv $encrypted_f0da1fbc7955_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
deploy:
  provider: script
  skip_cleanup: true
  script:
  - chmod 600 id_rsa;
  - scp -o StrictHostKeyChecking=no -i id_rsa docker-compose.yml ubuntu@poissontris.linards.net:~/
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export $SERVICE=poissontris; else $SERVICE=poissontris-test; fi
  - ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@poissontris.linards.net "docker-compose down; docker-compose -d up $SERVICE"
