dist: bionic

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull $DOCKER_USERNAME/poissontris:latest
    - docker build -t $DOCKER_USERNAME/poissontris --build-arg CACHE_DATE=$(date) --cache-from $DOCKER_USERNAME/poissontris:latest .
    - docker images
    - docker push $DOCKER_USERNAME/poissontris
before_install:
  - openssl aes-256-cbc -K $encrypted_f0da1fbc7955_key -iv $encrypted_f0da1fbc7955_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 id_rsa && ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@poissontris.linards.net
    ./deploy.sh
  on:
    branch: master
