version: '2'
volumes:
  poissontris:
  poissontris-test:

services:
  poissontris:
    restart: always
    image: linards/poissontris:latest
    expose:
     - 80
    volumes:
     - poissontris:/usr/lib/poissontris
    environment:
      - VIRTUAL_HOST=${POISSONTRIS_HOST}
      - LETSENCRYPT_HOST=${POISSONTRIS_HOST}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    working_dir: "/usr/lib/poissontris"
    command: "R -e \"options(shiny.port = 80, shiny.host = '0.0.0.0'); library(poissontris); runPoissontris()\""
  poissontris-test:
    restart: always
    image: linards/poissontris:test
    expose:
     - 80
    volumes:
     - poissontris-test:/usr/lib/poissontris
    environment:
      - VIRTUAL_HOST=${POISSONTRIS_TEST_HOST}
      - LETSENCRYPT_HOST=${POISSONTRIS_TEST_HOST}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    working_dir: "/usr/lib/poissontris"
    command: "R -e \"options(shiny.port = 80, shiny.host = '0.0.0.0'); library(poissontris); runPoissontris()\""

networks:
  default:
    external:
      name: nginx-proxy
